package com.verkoop.utils


object AppConstants{
     const val IMAGE_URL = "http://verkoopadmin.com/VerkoopApp/"
     const val GOOGLE_API_KEY = "AIzaSyC6ezTSfIS-pq-VX9zyq2qATzKWXZaPJqc"
     const val USER_ID = "userId"
     const val USER_NAME = "userName"
     const val USER_EMAIL_ID = "userEmailId"
     const val API_TOKEN = "api_token"
     const val LOGIN_TYPE = "loginType"
     const val COMING_FROM = "coming_from"
     const val CATEGORY_LIST = "category_list"
     const val PAGER_POSITION = "pager_position"
     const val SELECTED_LIST = "selected_list"
     const val CATEGORY_NAME = "category_name"
     const val CATEGORY_ID = "category_id"
     const val SUB_CATEGORY_ID = "SUB_CATEGORY_ID"
     const val TRANSACTION = "transaction"
     const val ADDRESS = "ADDRESS"
     const val LATITUDE = "LATITUDE"
     const val LONGITUDE = "LONGITUDE"
     const val ITEM_ID = "item_id"
     const val TYPE = "type"
     const val SUB_CATEGORY = "sub_category"
     const val POST_DATA = "post_data"
     const val REJECT_LIST = "REJECT_LIST"
     const val CITY_LIST = "CITY_LIST"
     const val CITY_NAME = "CITY_NAME"
     const val CITY_ID = "CITY_ID"
     const val STATE_NAME = "STATE_NAME"
     const val STATE_ID = "STATE_ID"
     const val COUNTRY_ID = "COUNTRY_ID"
     const val COUNTRY_NAME = "COUNTRY_NAME"
     const val COMMENT_RESULR = "COMMENT_RESULR"
     const val REPORT_LIST = "REPORT_LIST"
     const val ADAPTER_POSITION = "ADAPTER_POSITION"
     const val COMING_TYPE = "COMING_TYPE"
     const val PRODUCT_DETAIL = "PRODUCT_DETAIL"
     const val CAR_BRAND_NAME = "CAR_BRAND_NAME"
     const val CAR_BRAND_ID = "CAR_BRAND_ID"
     const val CAR_TYPE = "CAR_TYPE"
     const val CAR_TYPE_ID = "CAR_TYPE_ID"
     const val ZONE = "ZONE"
     const val ZONE_ID = "ZONE_ID"
}