package com.verkoop.utils


object AppConstants{
     const val IMAGE_URL = "http://verkoopadmin.com/VerkoopApp/"
     const val GOOGLE_API_KEY = "AIzaSyC6ezTSfIS-pq-VX9zyq2qATzKWXZaPJqc"
     const val USER_ID = "userId"
     const val USER_NAME = "userName"
     const val USER_EMAIL_ID = "userEmailId"
     const val API_TOKEN = "api_token"
     const val LOGIN_TYPE = "loginType"
     const val COMING_FROM = "coming_from"
     const val CATEGORY_LIST = "category_list"
     const val PAGER_POSITION = "pager_position"
     const val SELECTED_LIST = "selected_list"
     const val CATEGORY_NAME = "category_name"
     const val CATEGORY_ID = "category_id"
     const val SUB_CATEGORY_ID = "SUB_CATEGORY_ID"
     const val TRANSACTION = "transaction"
     const val ADDRESS = "ADDRESS"
     const val LATITUDE = "LATITUDE"
     const val LONGITUDE = "LONGITUDE"
     const val TYPE = "type"
     const val SUB_CATEGORY = "sub_category"
     const val POST_DATA = "post_data"
     const val REJECT_LIST = "REJECT_LIST"
     const val CITY_LIST = "CITY_LIST"
     const val CITY_NAME = "CITY_NAME"
     const val CITY_ID = "CITY_ID"
     const val STATE_NAME = "STATE_NAME"
     const val STATE_ID = "STATE_ID"
     const val COUNTRY_ID = "COUNTRY_ID"
     const val COUNTRY_NAME = "COUNTRY_NAME"
     const val COMMENT_RESULR = "COMMENT_RESULR"
     const val REPORT_LIST = "REPORT_LIST"
     const val ADAPTER_POSITION = "ADAPTER_POSITION"
     const val COMING_TYPE = "COMING_TYPE"
     const val PRODUCT_DETAIL = "PRODUCT_DETAIL"
     const val CAR_BRAND_NAME = "CAR_BRAND_NAME"
     const val CAR_BRAND_ID = "CAR_BRAND_ID"
     const val CAR_TYPE = "CAR_TYPE"
     const val CAR_TYPE_ID = "CAR_TYPE_ID"
     const val ZONE = "ZONE"
     const val ZONE_ID = "ZONE_ID"
     const val FILTER_ID = "FILTER_ID"
     const val FILTER_TYPE = "FILTER_TYPE"
     const val CAR_BRAND_LIST = "CAR_BRAND_LIST"
     const val PROFILE_URL = "PROFILE_URL"
     const val PRODUCT_URL = "PRODUCT_URL"
     const val PRODUCT_PRICE = "PRODUCT_PRICE"
     const val OFFERED_PRICE = "OFFERED_PRICE"
     const val PRODUCT_NAME = "PRODUCT_NAME"
     const val IS_MY_PRODUCT = "IS_MY_PRODUCT"
     const val IS_SOLD = "IS_SOLD"
     const val SCREEN_TYPE = "SCREEN_TYPE"
     const val MOBILE_NO = "MOBILE_NO"
     const val PICK_OPTION = "PICK_OPTION"


   /*Socket constant*/
     const val SOCKET_URL = "http://verkoopadmin.com:3000/"
     const val SOCKET_CONNECT = "SOCKET_CONNECT"
     const val SEND_MESSAGES = "messages"
     const val CHAT_LIST = "messagelists"
     const val MAKE_OFFER_EVENT = "makeOffer"
     const val INIT_USER_ID = "init"
     const val RECEIVE_MESSAGE = "receiveMessage"
     const val INBOX_LIST_EVENT = "inboxList"
     const val ARCHIVE_CHAT_EVENT = "archiveChat"
     const val UN_ARCHIVE_CHAT_EVENT = "unarchiveChat"
     const val DELETE_CHAT_EVENT = "deleteChat"
     const val ACCEPT_OFFER_EVENT = "acceptOffer"
     const val CANCEL_OFFER_EVENT = "cancelledOffer"
     const val DECLINE_OFFER_EVENT = "declineOffer"
     const val EDIT_OFFER_EVENT = "editOffer"
     const val DIRECT_CHAT = "directChat"

     const val SENDER_ID = "sender_id"
     const val ITEM_ID = "item_id"

}